### ISSUE TITLE
dialog window can't be moved to secundary monitor

### ISSUE THREAD

**Issue by jellespijker** [5axes/UniversalCuraSettings#25]
# Plugin version
- 0.15

# Cura version
- 4.10
- 4.11
- 4.12

# Platform

- Computer: Lenova ideaPad i7 GeForce MX230/Intel UHD Graphic 620 with external monitor
  - Using optimus to switch between graphic drivers
- Desktop: KDE
- OS: Linux 5.14.10-1-MANJARO \#1 SMP PREEMPT Thu Oct 7 06:43:34 UTC 2021 x86_64 GNU/Linux

# Reproduction steps
- Open dialog from Cura menu
- Try moving the dialog to another monitor

# Actual result
The dialog always opens up on the "main" monitor and can't be moved

# Expected result
Movable dialog between monitors.

**Comment by 5axes** [comment]
I have the same type of problem. if Cura is open on the Second monitor the dialog always open on the first one. It's a workaround in this case.

**Comment by 5axes** [comment]
Ok Solved !Need to remove the Automatic position at the center of the Windows.  But could have some different user experience Next time the windows will be opened at your previous position ... And expecting to get it into your Cura windows .

Pro/cons ?
