### ISSUE TITLE
Feature Request: Setting for OVERHANGS & Surface finish

### ISSUE THREAD

**Issue by inspectionsbybob** [5axes/UniversalCuraSettings#29]
Two more configurations I would like to see

- Overhangs

- Surface Finish (not just ironing, external wall finishes as well...)

**Comment by 5axes** [comment]
Nice idea concerning surface finish but perhaps could be included in the actual ironing intent

**Comment by inspectionsbybob** [comment]
Ironing is only for Horizontal surfaces, I was thinking about "Outer Wall" type surfaces.  Cura also has a few other settings that assist (horizontal)  ironing, but there are many other settings that affect (vertical)  outer wall. Speed, inner before outer, setback, line width and many more...

**Comment by 5axes** [comment]
Mode extra quality
+
Mode Top Surface
